```{r}
library(nflverse)
library(tidyverse)
library(ggrepel)
data <- load_pbp(2023)
```

```{r}
library(ggimage)
```

```{r}
data <- data %>% 
  filter(two_point_attempt == 1) %>%
  filter(penalty == 0)
```

```{r}
data <- data %>%
  group_by(posteam) %>%
  mutate(attempts = n())
```

```{r}
teams <- load_teams()
data <- data %>% 
  rename(team_abbr = posteam) %>%
  left_join(teams)
```

```{r}
#Making the plot
data %>%
ggplot() +
  geom_bar(mapping = aes(fill = two_point_conv_result, x = two_point_attempt, y = reorder(team_abbr, attempts)), position = "stack", stat = "identity") +
    scale_fill_manual(values=c("#de4a3a", "#42bd63")) +
  theme_bw() +
  geom_image(mapping = aes(x = attempts, y = reorder(team_abbr, attempts), image = team_logo_espn), size = 0.08) + 
  labs(
    x = "Number of 2-Point Tries",
    y = "Team",
    title = "The 2023 2-Point Tries",
    subtitle = "2023 Regular sans Super Bowl | Excluding Penalties",
    caption = "Data from nflverse | Graphic by Alex McKeever",
    fill = "Result"
 ) 




```

```         
```
